dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
language: ruby
sudo: false
bundler: true

script: bundle exec rake

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
